// Generated by jextract

package cubiomes.ffm;

/**
 * {@snippet lang=c :
 * typedef struct _div_t {
 *     int quot;
 *     int rem;
 * } div_t
 * }
 */
public class div_t extends _div_t {

    div_t() {
        // Should not be called directly
    }
}

