// Generated by jextract

package cubiomes.ffm;

/**
 * {@snippet lang=c :
 * typedef _Lldiv_t imaxdiv_t
 * }
 */
public class imaxdiv_t extends _Lldiv_t$3 {

    imaxdiv_t() {
        // Should not be called directly
    }
}

